<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

**Exercise 1 (Total recall)**

Term | Brief description
:-   | :-
Subsetting | To select elements
Indexing | To select one element
Slicing | To select a range of elements
Masking | Creating a filter to select elements that fit a certain criteria from a numpy array

**Exercise 2 (Show me the ‘odd’ letters)**

Use masking to subset the letters that correspond to the odd numbers. I.e., get the result `[A, C, E, G, I]`.

This is a slightly tricky problem because arrays are fussy about type. So, let me give you a recipe to solve this problem.

1. Subset all the first elements.
    - You should get `array(['1', '3', '2', ..., '10', '9'])`
2. Convert this to integers using astype(int)
    - You must look up how `astype()` works.
3. Use % to get the remainder for division by 2.
    - You should get `array([1, 1, 0, ..., 0, 1])`.
4. Use the previous result to create a mask that checks if the remainder is zero or not
    - You should get `array([True, True, False, ..., False, True])`.
5. Now you have identified the locations of the odd numbers.
    - Use the mask and extract the corresponding second elements.

In [17]:
import numpy as np


np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
num1 = np.array(np_array_2d[:, 0])
num2 = num1.astype(int)
num3 = num2 % 2
mask = num3 != 0
print(np_array_2d[mask, 1])

['A' 'C' 'E' 'G' 'I']


**Exercise 3**

Consider the 2D array shown above. Using your knowledge of NumPy masking, change:

1. values below 50 to -1,
2. values above 50 to +1, and
3. values equal to 50 to 0.

You should end up with:
```
[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
```

In [33]:
n = np.array([
    [66, 50, 57, -1, -1],
    [92, -1, 88, -1, -1],
    [75, -1, -1, 76, -1],
    [-1, 51, 87, -1, -1],
    [71, -1, 67, -1, 69]
])

n[n < 50] = -1
n[n > 50] = 1
n[n == 50] = 0
print(n)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
